url: https://enpro-research.github.io
baseurl: ""

plugins:
  - jekyll-polyglot

# Site settings
title: ENPro - Energy Neutral Production
email: info@fh-ooe.at
description: "FTI project 'ENPro - Energy Neutral Production' by University of Applied Sciences Upper Austria - Center of Execellence for Smart Production"
lang: de

languages: ["de", "en"]
default_lang: "de"
exclude_from_localization: ["assets/img"]
parallel_localization: false

sass:
  sourcemap: never

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: ENPro - Energy Neutral Production
  - line: University of Applied Sciences Upper Austria
  - line: Roseggerstraße 15, 4600 Wels Austria

# Build settings
markdown: kramdown
permalink: pretty